### ISSUE TITLE
No receipt for 'com.apple.pkg.CLTools_Executables' during installation on MacOS

### ISSUE THREAD

**Issue by kettanaito** [victorhqc/language-prisma#4]
## Current behavior

When installing `language-prisma` via Atom's packages, I get the following exception:

```
> tree-sitter-prisma@1.0.0 install /private/var/folders/mh/mfyzksxs34jfv5znybsfp_fr0000gn/T/apm-install-dir-20201016-2586-1dr27he.uddp/node_modules/language-prisma/node_modules/tree-sitter-prisma
> node-gyp rebuild


No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/mh/mfyzksxs34jfv5znybsfp_fr0000gn/T/apm-install-dir-20201016-2586-1dr27he.uddp/node_modules/language-prisma/node_modules/tree-sitter-prisma
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/mh/mfyzksxs34jfv5znybsfp_fr0000gn/T/apm-install-dir-20201016-2586-1dr27he.uddp/package.json'
npm WARN apm-install-dir-20201016-2586-1dr27he.uddp No description
npm WARN apm-install-dir-20201016-2586-1dr27he.uddp No repository field.
npm WARN apm-install-dir-20201016-2586-1dr27he.uddp No README data
npm WARN apm-install-dir-20201016-2586-1dr27he.uddp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-prisma@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-prisma@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.atom/.apm/_logs/2020-11-16T08_38_24_812Z-debug.log
```

## System

- MacOS Catalyna 10.15.5 (19F101)
- Atom 1.53.0
- language-prisma 0.1.2

**Comment by victorhqc** [comment]
Hello @kettanaito ! The package uses `electron-rebuild` which in turn uses some node-gyp to re-compile some native dependencies. Can you take a look at [this docs](https://github.com/nodejs/node-gyp#installation), maybe there's something not installed in your machine.

**Comment by jonohewitt** [comment]
I just had the same issue on Big Sur 11.2.1. 

I managed to install fine after downloading Command Line Tools for Xcode from [https://developer.apple.com/download/more/?=for%20Xcode](https://developer.apple.com/download/more/?=for%20Xcode) - it might be necessary to have an Apple developer account to access this page. It could probably be helpful to include a note about this requirement in the readme. 

Thanks for the package and the solution above!
