### ISSUE TITLE
Bug: tree-sitter-prisma@1.0.0 install script.

### ISSUE THREAD

**Issue by pi0neerpat** [victorhqc/language-prisma#5]
On clean install of Ubuntu and Atom, this package fails to install. I've seen node-gyp errors before. Maybe there is a missing dependency?

```
Atomc v1.53.0
language prisma v0.1.2
Ubuntu v20.04 LTS
Gnome v3.36.1
```

```
> tree-sitter-prisma@1.0.0 install /tmp/apm-install-dir-20201018-2813-10fsj7c.x2ny/node_modules/language-prisma/node_modules/tree-sitter-prisma
> node-gyp rebuild


gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:165:21)
gyp ERR! System Linux 5.4.0-54-generic
gyp ERR! command "/snap/atom/265/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/265/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20201018-2813-10fsj7c.x2ny/node_modules/language-prisma/node_modules/tree-sitter-prisma
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-20201018-2813-10fsj7c.x2ny/package.json'
npm WARN apm-install-dir-20201018-2813-10fsj7c.x2ny No description
npm WARN apm-install-dir-20201018-2813-10fsj7c.x2ny No repository field.
npm WARN apm-install-dir-20201018-2813-10fsj7c.x2ny No README data
npm WARN apm-install-dir-20201018-2813-10fsj7c.x2ny No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-prisma@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-prisma@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.atom/.apm/_logs/2020-11-18T16_54_01_254Z-debug.log
```

**Comment by victorhqc** [comment]
Hello @pi0neerpat the package uses `electron-rebuild` to rebuild some native dependencies used to compile to the target's machine. Unfortunately it requires some dependencies to be installed on your machine according to [this](https://github.com/nodejs/node-gyp#installation) documentation. Looking at the error seems that `make` is not installed.
